version = "0.2"
package = "tube"
authors = "Pedro R. Andrade"
contact = "pedro.andrade@inpe.br"
content = "Implements the water in the tube model from the book Thinking in Systems, by Donella Meadows."
