version = "0.2"
package = "tube"
license = "GPL"
title = "Water in the Tube"
depends = "terrame (>= 2.0)"
date = "30 April 2015"
authors = "Pedro R. Andrade"
contact = "pedro.andrade@inpe.br"
content = "Implements the water in the tube model from the book Thinking in Systems, by Donella Meadows."
